function showContent(){
    document.getElementById('text').innerHTML='Hey! This is me..';
  }
  function hideContent(){
    document.getElementById('text').innerHTML='';
  }
  function smallcontent(){
    document.getElementById('text').style.fontSize='25px';
  }
  function mediumcontent(){
    document.getElementById('text').style.fontSize='50px';
  }
  function largecontent(){
    document.getElementById('text').style.fontSize='100px';
  }